# Site settings
title: Learning Machine Learning
email: luiz.gh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Blog posts on Machine Learning. Deep Learning for Computer Vision - libraries, models and ideas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luizgh.github.io.com" # the base hostname & protocol for your site
#twitter_username: luizgh
github_username:  luizgh

# Build settings
markdown: kramdown
permalink: pretty
